[project]
name = "context-libra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markitdown>=0.1.3",
    "numpy>=2.3.4",
    "psycopg2>=2.9.11",
    "python-dotenv>=1.2.1",
    "sudachidict-core>=20251022",
    "sudachipy>=0.6.10",
]
